# Generated by Django 5.1.2 on 2024-11-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_servicoadicional_servico_servicos_adicionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='protocole',
        ),
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'Trocar válvula do motor'), ('TO', 'Troca de óleo'), ('B', 'Balanceamento')], max_length=3),
        ),
    ]
