# Generated by Django 5.1.2 on 2024-11-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_remove_servico_protocole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='protocolo',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
