# Generated by Django 5.1.2 on 2024-11-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_servico_protocolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='servicos_adicionais',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='protocolo',
            new_name='protocole',
        ),
        migrations.DeleteModel(
            name='ServicoAdicional',
        ),
    ]
