# Generated by Django 5.1.2 on 2024-11-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_remove_servico_servicos_adicionais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'Trocar válvula do motor'), ('TO', 'Troca de óleo'), ('B', 'Balanceamento'), ('LC', 'Lavagem')], max_length=3),
        ),
    ]
